# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewer', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.TextField(default='A nice message.'),
        ),
    ]
