# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviewer', '0003_auto_20171023_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
